---
title: "PS ESTAT"
author: "Marina Bráulio (231027319)"
date: "2023-10-05"
output: html_document
---

Carregando os Pacotes
```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(readr)
```

Carregando os Bancos de Dados
```{r}
vendas = read.csv("vendas.csv")
devolucao1 = read.csv("devolução.csv")
```

Tema ESTAT
```{r}
cores_estat <- c("#A11D21", "#003366", "#CC9900", "#663333", "#FF6600", "#CC9966", "#999966", "#006606", "#008091", "#041835", "#666666")
theme_estat <- function(...) {
    theme <- ggplot2::theme_bw() +
        ggplot2::theme(
            axis.title.y = ggplot2::element_text(colour = "black", size = 12),
            axis.title.x = ggplot2::element_text(colour = "black", size = 12),
            axis.text = ggplot2::element_text(colour = "black", size = 9.5),
            panel.border = ggplot2::element_blank(),
            axis.line = ggplot2::element_line(colour = "black"),
            legend.position = "top",
            ...
        )

    return(
        list(
            theme,
            scale_fill_manual(values = cores_estat),
            scale_colour_manual(values = cores_estat)
        )
    )
}
```


Tratando os Dados - Vendas
```{r}
str(vendas)

vendas = vendas %>% 
  select(!c( X, ...1.x, ...1.y))

colnames(vendas)[colnames(vendas) == "Data.Venda"] <- "Data_da_Venda"
colnames(vendas)[colnames(vendas) == "User.ID"] <- "ID_do_Usuário"
colnames(vendas)[colnames(vendas) == "Product.ID"] <- "ID_do_Produto"
colnames(vendas)[colnames(vendas) == "Product.Name"] <- "Nome_do_Produto"
colnames(vendas)[colnames(vendas) == "Brand"] <- "Marca"
colnames(vendas)[colnames(vendas) == "Category"] <- "Categoria"
colnames(vendas)[colnames(vendas) == "Price"] <- "Preço"
colnames(vendas)[colnames(vendas) == "Rating"] <- "Avaliação"
colnames(vendas)[colnames(vendas) == "Color"] <- "Cor"
colnames(vendas)[colnames(vendas) == "Size"] <- "Tamanho"
colnames(vendas)[colnames(vendas) == "Unique.ID"] <- "ID_Único"
colnames(vendas)[colnames(vendas) == "Motivo.devolução"] <- "Motivo_da_devolução"

vendas$Nome_do_Produto <- as.factor(vendas$Nome_do_Produto) 
levels(vendas$Nome_do_Produto) <- c("Vestido", "Jeans", "Sapatos", "Casacos", "Blusas")
levels(vendas$Nome_do_Produto)
vendas$Nome_do_Produto <- as.character(vendas$Nome_do_Produto)

vendas$Categoria <- as.factor(vendas$Categoria) 
levels(vendas$Categoria) <- c("Moda Infantil", "Moda Masculina", "Moda Feminina")
levels(vendas$Categoria)
vendas$Categoria <- as.character(vendas$Categoria)

vendas$Cor <- as.factor(vendas$Cor) 
levels(vendas$Cor) <- c("Preta", "Azul", "Verde", "Vermelha", "Branca", "Amarela")
levels(vendas$Cor)
vendas$Cor <- as.character(vendas$Cor)

vendas$Tamanho <- as.factor(vendas$Tamanho) 
levels(vendas$Tamanho) <- c("Grande", "Médio", "Pequeno", "Extra Grande")
levels(vendas$Tamanho)
vendas$Tamanho <- as.character(vendas$Tamanho)
```

Tratando os Dados - Devolução
```{r}
str(devolucao1)
devolucao = devolucao1 %>% 
  select(!c( X, ...1))
colnames(devolucao)[colnames(devolucao) == "Unique.ID"] <- "ID_Único"
colnames(devolucao)[colnames(devolucao) == "Motivo.devolução"] <- "Motivo_da_devolução"
```


Comparando e Analisando os bancos:
```{r}
sum(!is.na(vendas$Motivo_da_devolução))
sum(!is.na(devolucao$Motivo_da_devolução))
#Nota-se que os dois possuem quantidades diferentes
sum(duplicated(vendas))
#Essa função mostra que algumas linhas estão repetidas e por isso temos que tratá-las
dados = distinct(vendas)
#Para conferir se não existem mais linhas repetidas
sum(duplicated(dados))
#Usaremos a partir daqui, o banco "dados"
```

1 - Faturamento anual por categoria 
```{r}
dados$Data_da_Venda = mdy(dados$Data_da_Venda)
dados = dados %>% 
  mutate(Mês = month(Data_da_Venda))
linhas = dados %>% 
  filter(!is.na(Preço)) %>%
  filter(!is.na(Categoria)) %>%
  group_by(Mês, Categoria) %>% 
  summarise(Faturamento = sum(Preço)) %>% 
  filter(!is.na(Mês))

linhas$Mês= as.factor(linhas$Mês)
levels(linhas$Mês) = c("Jan", "Fev", "Mar", "Abr", "Maio", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez")
levels(linhas$Mês)

ggplot(linhas) +
  aes(x = Mês, y = Faturamento, group = Categoria, colour = Categoria) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_colour_manual(name = "Categoria", labels = c("A", "B", "C")) +
  labs(x = "Mês", y = "Faturamento")+
  theme_estat() 
ggsave("linhas_bivariado.pdf", width = 158, height = 93, units = "mm")
```


1 - Variação do preço por marca 
```{r}
dados1 = dados %>% 
    filter(!is.na(Categoria)) %>% 
    filter(!is.na(Marca)) %>% 
    filter(!is.na(Nome_do_Produto))
  
ggplot(dados1) +
  aes(x = Nome_do_Produto, y = Preço) +
  geom_boxplot(fill = c("#A11D21"), width = 0.5) +
  facet_wrap(~ Marca) +
  stat_summary(
    fun = "mean", geom = "point", shape = 23, size = 3, fill = "white"
  ) +
  labs(x = "Tipos de produtos", y = "Preço (em Reais)") +
  theme_estat() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("boxplot.pdf", width = 158, height = 93, units = "mm")
```

```{r}
dados1 = dados %>% 
    filter(!is.na(Categoria)) %>% 
    filter(!is.na(Marca)) %>% 
    filter(!is.na(Nome_do_Produto))
  
ggplot(dados1) +
  aes(x = Marca, y = Preço) +
  geom_boxplot(fill = c("#A11D21"), width = 0.5) +
  facet_wrap(~ Nome_do_Produto) +
  stat_summary(
    fun = "mean", geom = "point", shape = 23, size = 3, fill = "white"
  ) +
  labs(x = "Marca", y = "Preço (em Reais)") +
  theme_estat() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("boxplot.pdf", width = 158, height = 93, units = "mm")
```

```{r}
dados1 = dados %>% 
    filter(!is.na(Categoria)) %>% 
    filter(!is.na(Marca)) %>% 
    filter(!is.na(Nome_do_Produto))
  
ggplot(dados1) +
  aes(x = Marca, y = Preço) +
  geom_boxplot(fill = c("#A11D21"), width = 0.5) +
  stat_summary(
    fun = "mean", geom = "point", shape = 23, size = 3, fill = "white"
  ) +
  labs(x = "Marca", y = "Preço (em Reais)") +
  theme_estat() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("boxplot.pdf", width = 158, height = 93, units = "mm")
```
Cálculo de medidas resumo para cada marca - 
```{r}
# Adida
adidas = dados1 %>% 
  filter(Marca == "Adidas")
  #Marca num geral
resumo_adidas_geral = summary(adidas$Preço)
resumo_adidas_geral
  #Marca por produto
resumo_adidas_segmentado <- tapply(adidas$Preço, adidas$Nome_do_Produto, summary)
resumo_adidas_segmentado
````
```{r}
# Gucci
gucci = dados1 %>% 
  filter(Marca == "Gucci")
  #Marca num geral
resumo_gucci_geral = summary(gucci$Preço)
resumo_gucci_geral
  #Marca por produto
resumo_gucci_segmentado <- tapply(gucci$Preço, gucci$Nome_do_Produto, summary)
resumo_gucci_segmentado
````

```{r}
# H&M
hm = dados1 %>% 
  filter(Marca == "H&M")
  #Marca num geral
resumo_HM_geral = summary(hm$Preço)
resumo_HM_geral
  #Marca por produto
resumo_HM_segmentado <- tapply(gucci$Preço, gucci$Nome_do_Produto, summary)
resumo_HM_segmentado
````

```{r}
# Nike
nike = dados1 %>% 
  filter(Marca == "Nike")
  #Marca num geral
resumo_nike_geral = summary(nike$Preço)
resumo_nike_geral
  #Marca por produto
resumo_nike_segmentado <- tapply(gucci$Preço, gucci$Nome_do_Produto, summary)
resumo_nike_segmentado
````
```{r}
# Zara
zara = dados1 %>% 
  filter(Marca == "Zara")
  #Marca num geral
resumo_zara_geral = summary(zara$Preço)
resumo_zara_geral
  #Marca por produto
resumo_zara_segmentado <- tapply(gucci$Preço, gucci$Nome_do_Produto, summary)
resumo_zara_segmentado

```

